fail_fast: true
# exclude: ^(vendor/|circles-config/|circles-locale|docs/)
repos:
- repo: 'https://github.com/dnephin/pre-commit-golang'
  rev: v0.5.0
  hooks:
  - id: go-build
  - id: go-mod-tidy
  - id: go-imports
  - id: go-fmt
  - id: go-unit-tests
  - id: golangci-lint

- repo: 'https://github.com/pre-commit/pre-commit-hooks'
  rev: v4.1.0
  hooks:
  - id: trailing-whitespace
  - id: check-yaml
  - id: check-merge-conflict
  - id: check-json
